//user
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FALIED = "USER_SIGN_IN_FALIED";
export const USER_GOOGLE_SIGN_IN_START = "USER_GOOGLE_SIGN_IN_START";
export const USER_EMAIL_SIGN_IN_START = "USER_EMAIL_SIGN_IN_START";
export const USER_SIGN_OUT_START = "USER_EMAIL_SIGN_OUT_START";
export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS";
export const USER_SIGN_OUT_FAILED = "USER_SIGN_OUT_FAILED";
export const USER_SIGN_UP_START = "USER_SIGN_UP_START";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FALIED = "USER_SIGN_UP_FALIED";

//cart
export const CART_TOGGLE_DROPDOWN = "CART_TOGGLE_DROPDOWN";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_TO_CART = "REMOVE_ITEM_TO_CART";
export const CLEAR_ITEM_OF_CART = "CLEAR_ITEM_OF_CART";
export const SIGN_OUT_CLEAR_CART = "SIGN_OUT_CLEAR_CART";

//shop
export const GET_SHOP_DATA_START = "GET_SHOP_DATA_START";
export const GET_SHOP_DATA_SUCCESS = "GET_SHOP_DATA_SUCCESS";
export const GET_SHOP_DATA_FAILED = "GET_SHOP_DATA_FAILED";
export const GET_SHOP_DATA_INITIAL = "GET_SHOP_DATA_INITIAL";
export const CHECK_USER_AUTHENTICATED = "CHECK_USER_AUTHENTICATED";
