export const USER_AUTHENTICATED = "USER_AUTHENTICATED";

export const CART_TOGGLE_DROPDOWN = "CART_TOGGLE_DROPDOWN";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_TO_CART = "REMOVE_ITEM_TO_CART";
export const CLEAR_ITEM_OF_CART = "CLEAR_ITEM_OF_CART";
